-- Sample Users for Testing BPS Assessment System
-- Contains basic test users for development and testing

-- Sample Admin User
INSERT INTO users (
    id, nip, nama, email, password, role, roles, primaryRole,
    jenisKelamin, tanggalLahir, alamat, mobilePhone, pendidikanTerakhir,
    jabatan, golongan, status, instansi, kantor, username, isActive, 
    createdAt, updatedAt
) VALUES (
    'admin_test_001',
    '199999999999999999',
    'Admin Test User',
    'admin.test@bps.go.id',
    '$2b$10$hash_password_here',
    'ADMIN',
    ARRAY['ADMIN'],
    'ADMIN',
    'LK',
    '1990-01-01',
    'Jl. Test Admin No. 1',
    '081234567890',
    'S1 Informatika',
    'Administrator Sistem',
    'IV/a',
    'PNS',
    'BPS Kabupaten Pringsewu',
    'BPS Kabupaten Pringsewu',
    'admin.test',
    true,
    NOW(),
    NOW()
);

-- Sample Pimpinan User
INSERT INTO users (
    id, nip, nama, email, password, role, roles, primaryRole,
    jenisKelamin, tanggalLahir, alamat, mobilePhone, pendidikanTerakhir,
    jabatan, golongan, status, instansi, kantor, username, isActive,
    createdAt, updatedAt
) VALUES (
    'pimpinan_test_001',
    '197001011990031001',
    'Pimpinan Test User',
    'pimpinan.test@bps.go.id',
    '$2b$10$hash_password_here',
    'PIMPINAN',
    ARRAY['PIMPINAN'],
    'PIMPINAN',
    'LK',
    '1970-01-01',
    'Jl. Test Pimpinan No. 1',
    '081234567891',
    'S2 Statistik',
    'Kepala BPS Test',
    'IV/c',
    'PNS',
    'BPS Kabupaten Pringsewu',
    'BPS Kabupaten Pringsewu',
    'pimpinan.test',
    true,
    NOW(),
    NOW()
);

-- Sample Staff Users (5 users for testing)
INSERT INTO users (
    id, nip, nama, email, password, role, roles, primaryRole,
    jenisKelamin, tanggalLahir, alamat, mobilePhone, pendidikanTerakhir,
    jabatan, golongan, status, instansi, kantor, username, isActive,
    createdAt, updatedAt
) VALUES 
(
    'staff_test_001',
    '198501011999031001',
    'Staff Test Satu',
    'staff1.test@bps.go.id',
    '$2b$10$hash_password_here',
    'STAFF',
    ARRAY['STAFF'],
    'STAFF',
    'LK',
    '1985-01-01',
    'Jl. Test Staff No. 1',
    '081234567892',
    'S1 Statistik',
    'Statistisi Ahli Muda',
    'III/c',
    'PNS',
    'BPS Kabupaten Pringsewu',
    'BPS Kabupaten Pringsewu',
    'staff1.test',
    true,
    NOW(),
    NOW()
),
(
    'staff_test_002',
    '198502021999032002',
    'Staff Test Dua',
    'staff2.test@bps.go.id',
    '$2b$10$hash_password_here',
    'STAFF',
    ARRAY['STAFF'],
    'STAFF',
    'PR',
    '1985-02-02',
    'Jl. Test Staff No. 2',
    '081234567893',
    'S1 Ekonomi',
    'Statistisi Ahli Muda',
    'III/c',
    'PNS',
    'BPS Kabupaten Pringsewu',
    'BPS Kabupaten Pringsewu',
    'staff2.test',
    true,
    NOW(),
    NOW()
),
(
    'staff_test_003',
    '198503031999033003',
    'Staff Test Tiga',
    'staff3.test@bps.go.id',
    '$2b$10$hash_password_here',
    'STAFF',
    ARRAY['STAFF'],
    'STAFF',
    'LK',
    '1985-03-03',
    'Jl. Test Staff No. 3',
    '081234567894',
    'D3 Statistik',
    'Statistisi Terampil',
    'II/c',
    'PNS',
    'BPS Kabupaten Pringsewu',
    'BPS Kabupaten Pringsewu',
    'staff3.test',
    true,
    NOW(),
    NOW()
),
(
    'staff_test_004',
    '198504041999034004',
    'Staff Test Empat',
    'staff4.test@bps.go.id',
    '$2b$10$hash_password_here',
    'STAFF',
    ARRAY['STAFF'],
    'STAFF',
    'PR',
    '1985-04-04',
    'Jl. Test Staff No. 4',
    '081234567895',
    'S1 Komputer',
    'Pranata Komputer Ahli Muda',
    'III/b',
    'PNS',
    'BPS Kabupaten Pringsewu',
    'BPS Kabupaten Pringsewu',
    'staff4.test',
    true,
    NOW(),
    NOW()
),
(
    'staff_test_005',
    '198505051999035005',
    'Staff Test Lima',
    'staff5.test@bps.go.id',
    '$2b$10$hash_password_here',
    'STAFF',
    ARRAY['STAFF'],
    'STAFF',
    'LK',
    '1985-05-05',
    'Jl. Test Staff No. 5',
    '081234567896',
    'S1 Manajemen',
    'Analis Pengelolaan Keuangan APBN',
    'III/a',
    'PPPK',
    'BPS Kabupaten Pringsewu',
    'BPS Kabupaten Pringsewu',
    'staff5.test',
    true,
    NOW(),
    NOW()
);